### ISSUE TITLE
Usage. 

### ISSUE THREAD

**Issue by CalvinBreezy** [lens-network/lens-node#2]
Docker

docker-compose --file testnet-external-node.yml up -d

docker-compose command is outdated. This type of syntax was used before modern versions of docker. 

Starting from docker 20.10.0v that was issued in 2020, 
It’s necessary to execute docker compose as: 

docker compose --file testnet-external-node.yml up -d

**Comment by skynnes** [comment]
Fixed in the readme, thanks for raising!
